const mongoose = require('mongoose');

// Helper to create date relative to today
const daysAgo = (d) => new Date(Date.now() - d * 24 * 60 * 60 * 1000);
const daysFromNow = (d) => new Date(Date.now() + d * 24 * 60 * 60 * 1000);

const contractorsData = [
  {
    contractorId: 'CON-001',
    name: 'Patel Infrastructure Pvt Ltd',
    company: 'Patel Infra Group',
    contact: '+91 98250 12345',
    email: 'contact@patelinfra.gujarat.in',
    specialization: 'Bridge Engineering & Rehabilitation',
    isActive: true,
    isDemo: true
  },
  {
    contractorId: 'CON-002',
    name: 'Sadbhav Engineering Ltd',
    company: 'Sadbhav Infra Works',
    contact: '+91 98251 23456',
    email: 'tenders@sadbhav.co.in',
    specialization: 'Highway Resurfacing & Heavy Pavement',
    isActive: true,
    isDemo: true
  },
  {
    contractorId: 'CON-003',
    name: 'PSP Projects Ltd',
    company: 'PSP Construction & Infra',
    contact: '+91 98252 34567',
    email: 'projects@pspprojects.com',
    specialization: 'Government Administrative Buildings & Institutional Structures',
    isActive: true,
    isDemo: true
  },
  {
    contractorId: 'CON-004',
    name: 'Dilip Buildcon Gujarat Division',
    company: 'Dilip Buildcon Ltd',
    contact: '+91 98253 45678',
    email: 'gujarat@dilipbuildcon.com',
    specialization: 'Expressways, Grade Separators & Highway Widening',
    isActive: true,
    isDemo: true
  },
  {
    contractorId: 'CON-005',
    name: 'Cube Construction Engineering Ltd',
    company: 'Cube Engineering Group',
    contact: '+91 98254 56789',
    email: 'info@cubeconstruction.in',
    specialization: 'RCC Box Culverts, Drainage & Water Retaining Infrastructure',
    isActive: true,
    isDemo: true
  },
  {
    contractorId: 'CON-006',
    name: 'Larsen & Toubro Heavy Civil Infra',
    company: 'L&T Construction',
    contact: '+91 98255 67890',
    email: 'gujarat.civil@lntecc.com',
    specialization: 'Cable-Stayed Bridges, Viaducts & Marine Structures',
    isActive: true,
    isDemo: true
  }
];

const usersData = [
  {
    name: 'Admin User',
    email: 'admin@gujrb.gov.in',
    role: 'Admin',
    district: null,
    passwordHash: 'demo',
    isActive: true,
    isDemo: true
  },
  {
    name: 'Er. Amit R. Mehta',
    email: 'officer.mehta@gujrb.gov.in',
    role: 'District Officer',
    district: 'Ahmedabad',
    passwordHash: 'demo',
    isActive: true,
    isDemo: true
  },
  {
    name: 'Mansi Shah',
    email: 'mansi.shah@gujrb.gov.in',
    role: 'District Officer',
    district: 'Gandhinagar',
    passwordHash: 'demo',
    isActive: true,
    isDemo: true
  },
  {
    name: 'Er. Rajesh V. Solanki',
    email: 'inspector.solanki@gujrb.gov.in',
    role: 'Field Inspector',
    district: 'Ahmedabad',
    passwordHash: 'demo',
    isActive: true,
    isDemo: true
  },
  {
    name: 'Er. Hardik Dave',
    email: 'inspector.dave@gujrb.gov.in',
    role: 'Field Inspector',
    district: 'Surat',
    passwordHash: 'demo',
    isActive: true,
    isDemo: true
  },
  {
    name: 'Er. Sneha M. Joshi',
    email: 'officer.joshi@gujrb.gov.in',
    role: 'District Officer',
    district: 'Vadodara',
    passwordHash: 'demo',
    isActive: true,
    isDemo: true
  }
];

const assetsData = [
  // ===================== BRIDGES =====================
  {
    assetId: 'BR-GJ-AHM-00001',
    name: 'Subhash Bridge - Sabarmati River Crossing',
    description: 'Vital 4-lane RCC continuous bridge connecting Dudheshwar and Sabarmati areas across River Sabarmati.',
    category: 'Bridges',
    type: 'RCC Girder Bridge',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Ahmedabad Division' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Ahmedabad', taluka: 'Sabarmati', division: 'Ahmedabad R&B Division 1', subdivision: 'Subdivision A' },
    location: { address: 'Subhash Bridge Circle, Sabarmati', landmark: 'Near Gandhi Ashram', latitude: 23.0592, longitude: 72.5801 },
    construction: { year: 1973, commissioningDate: new Date('1973-10-02'), originalCost: 450, contractor: 'Sadbhav Engineering Ltd', designLife: 50 },
    technical: { spanCount: 12, lengthMeters: 440, widthMeters: 18.5, loadClass: 'IRC Class 70R' },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 32,
      status: 'Critical',
      components: { physical: 12, safety: 8, age: 2, findings: 0, usage: 4, physicalRating: 2, safetyRating: 2 },
      lastInspectionDate: daysAgo(20),
      nextInspectionDate: daysAgo(5), // Overdue!
      maintenanceRecommended: true
    },
    lifecycleStatus: 'Under Maintenance',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BR-GJ-AHM-00002',
    name: 'Atal Pedestrian & Utility Suspension Bridge',
    description: 'Iconic foot overbridge and pedestrian landmark across Sabarmati Riverfront connecting East and West flowers parks.',
    category: 'Bridges',
    type: 'Steel Truss Suspension Bridge',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'Sabarmati Riverfront Development Corp & R&B' },
    administrative: { state: 'Gujarat', region: 'Central Gujarat', district: 'Ahmedabad', taluka: 'Daskroi', division: 'Ahmedabad Riverfront Wing', subdivision: 'Central Wing' },
    location: { address: 'Sabarmati Riverfront West, Ellisbridge Area', landmark: 'Between Ellis Bridge and Sardar Bridge', latitude: 23.0270, longitude: 72.5740 },
    construction: { year: 2022, commissioningDate: new Date('2022-08-27'), originalCost: 7400, contractor: 'PSP Projects Ltd', designLife: 75 },
    technical: { spanCount: 1, lengthMeters: 300, widthMeters: 14.0, loadClass: 'Pedestrian Heavy' },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 92,
      status: 'Good',
      components: { physical: 38, safety: 19, age: 15, findings: 15, usage: 7, physicalRating: 5, safetyRating: 5 },
      lastInspectionDate: daysAgo(60),
      nextInspectionDate: daysFromNow(305),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BR-GJ-AHM-00003',
    name: 'Ellis Bridge Heritage Overpass (West Flank)',
    description: 'Century-old historic steel bowstring arch bridge, restricted to utility and light municipal transport.',
    category: 'Bridges',
    type: 'Steel Bowstring Arch Bridge',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'Heritage Conservation & R&B Ahmedabad' },
    administrative: { state: 'Gujarat', region: 'Central Gujarat', district: 'Ahmedabad', taluka: 'Ellisbridge', division: 'Ahmedabad Division 2', subdivision: 'Subdivision B' },
    location: { address: 'Ellis Bridge Road, Paldi - Bhadra', landmark: 'Near Town Hall', latitude: 23.0245, longitude: 72.5721 },
    construction: { year: 1892, commissioningDate: new Date('1892-05-10'), originalCost: 40, contractor: 'Historical British Works / R&B Heritage', designLife: 100 },
    technical: { spanCount: 7, lengthMeters: 260, widthMeters: 10.2, loadClass: 'Restricted Light Load' },
    usage: { trafficImportance: 'Low' },
    condition: {
      score: 48,
      status: 'Poor',
      components: { physical: 18, safety: 10, age: 0, findings: 10, usage: 10, physicalRating: 2, safetyRating: 2 },
      lastInspectionDate: daysAgo(45),
      nextInspectionDate: daysAgo(10), // Overdue
      maintenanceRecommended: true
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BR-GJ-SRT-00004',
    name: 'Tapi River Cable-Stayed Bridge (Athwa-Adajan)',
    description: 'Signature 4-lane cable-stayed bridge spanning the holy River Tapi, connecting Athwagate and Adajan.',
    category: 'Bridges',
    type: 'Cable-Stayed Bridge',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'Surat City Special Infrastructure Wing' },
    administrative: { state: 'Gujarat', region: 'South Gujarat', district: 'Surat', taluka: 'Chorasi', division: 'Surat R&B City Division', subdivision: 'Cable Bridge Sub-unit' },
    location: { address: 'Athwa Lines to Adajan Main Link', landmark: 'Tapi Waterfront', latitude: 21.1925, longitude: 72.8010 },
    construction: { year: 2018, commissioningDate: new Date('2018-10-02'), originalCost: 14300, contractor: 'Larsen & Toubro Heavy Civil Infra', designLife: 80 },
    technical: { spanCount: 4, lengthMeters: 918, widthMeters: 21.0, loadClass: 'IRC Class 70R Double' },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 88,
      status: 'Good',
      components: { physical: 36, safety: 18, age: 14, findings: 15, usage: 5, physicalRating: 4, safetyRating: 5 },
      lastInspectionDate: daysAgo(90),
      nextInspectionDate: daysFromNow(275),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BR-GJ-SRT-00005',
    name: 'Sardar Vallabhbhai Patel Flyover, Majura Gate',
    description: 'Multi-level Y-junction flyover de-bottlenecking Ring Road traffic towards Surat Railway Station and Athwa.',
    category: 'Bridges',
    type: 'Pre-Stressed Concrete Flyover',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Surat' },
    administrative: { state: 'Gujarat', region: 'South Gujarat', district: 'Surat', taluka: 'Majura', division: 'Surat Highway Division', subdivision: 'Subdivision 1' },
    location: { address: 'Majura Gate Crossroad, Ring Road', landmark: 'Near New Civil Hospital', latitude: 21.1780, longitude: 72.8220 },
    construction: { year: 2012, commissioningDate: new Date('2012-04-15'), originalCost: 4800, contractor: 'Patel Infrastructure Pvt Ltd', designLife: 60 },
    technical: { spanCount: 18, lengthMeters: 1250, widthMeters: 17.2, loadClass: 'IRC Class AA' },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 72,
      status: 'Fair',
      components: { physical: 28, safety: 15, age: 12, findings: 10, usage: 7, physicalRating: 3, safetyRating: 4 },
      lastInspectionDate: daysAgo(120),
      nextInspectionDate: daysFromNow(245),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BR-GJ-BRC-00006',
    name: 'New Narmada River Extra-Dosed Bridge (NH-48)',
    description: 'State-of-the-art 6-lane extradosed bridge across River Narmada, parallel to the historic Golden Bridge at Bharuch-Ankleshwar.',
    category: 'Bridges',
    type: 'Extradosed Cable Bridge',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'Gujarat Special Projects Wing' },
    administrative: { state: 'Gujarat', region: 'South-Central Gujarat', district: 'Bharuch', taluka: 'Ankleshwar', division: 'Bharuch National Corridors', subdivision: 'Narmada Bridge Unit' },
    location: { address: 'NH-48 Narmada River Crossing, Ankleshwar-Bharuch Bypass', landmark: 'Adjacent to Golden Bridge', latitude: 21.6980, longitude: 72.9850 },
    construction: { year: 2017, commissioningDate: new Date('2017-03-07'), originalCost: 37900, contractor: 'Larsen & Toubro Heavy Civil Infra', designLife: 100 },
    technical: { spanCount: 10, lengthMeters: 1344, widthMeters: 22.8, loadClass: 'IRC Class 70R Multi-lane' },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 86,
      status: 'Good',
      components: { physical: 35, safety: 18, age: 14, findings: 15, usage: 4, physicalRating: 4, safetyRating: 5 },
      lastInspectionDate: daysAgo(75),
      nextInspectionDate: daysFromNow(290),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BR-GJ-VDR-00007',
    name: 'Mahi River Pre-Stressed Concrete Viaduct, Vasad',
    description: 'Major transit corridor over Mahi River connecting Vadodara and Anand industrial belt along SH-83.',
    category: 'Bridges',
    type: 'PSC Box Girder Bridge',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Vadodara Circle' },
    administrative: { state: 'Gujarat', region: 'Central Gujarat', district: 'Vadodara', taluka: 'Savli', division: 'Vadodara R&B Division', subdivision: 'Subdivision North' },
    location: { address: 'Vasad Mahi River Crossing, SH-83', landmark: 'Vasad Toll Junction', latitude: 22.4620, longitude: 73.0780 },
    construction: { year: 2004, commissioningDate: new Date('2004-11-19'), originalCost: 3200, contractor: 'Sadbhav Engineering Ltd', designLife: 60 },
    technical: { spanCount: 16, lengthMeters: 780, widthMeters: 14.5, loadClass: 'IRC Class 70R' },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 65,
      status: 'Fair',
      components: { physical: 25, safety: 14, age: 9, findings: 10, usage: 7, physicalRating: 3, safetyRating: 3 },
      lastInspectionDate: daysAgo(110),
      nextInspectionDate: daysFromNow(255),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BR-GJ-VDR-00008',
    name: 'Vishwamitri River Overbridge (Sayajigunj Link)',
    description: 'City overbridge spanning Vishwamitri River, suffering from expansion joint fatigue and approach settlement.',
    category: 'Bridges',
    type: 'RCC T-Beam Bridge',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Vadodara' },
    administrative: { state: 'Gujarat', region: 'Central Gujarat', district: 'Vadodara', taluka: 'Vadodara City', division: 'Vadodara City Division', subdivision: 'Sayaji Sector' },
    location: { address: 'Sayajigunj Overpass, Near Railway Station', landmark: 'Sayaji Baug North Gate', latitude: 22.3150, longitude: 73.1840 },
    construction: { year: 1989, commissioningDate: new Date('1989-08-15'), originalCost: 750, contractor: 'Cube Construction Engineering Ltd', designLife: 50 },
    technical: { spanCount: 6, lengthMeters: 220, widthMeters: 16.0, loadClass: 'IRC Class A' },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 52,
      status: 'Poor',
      components: { physical: 20, safety: 11, age: 5, findings: 10, usage: 6, physicalRating: 2, safetyRating: 3 },
      lastInspectionDate: daysAgo(35),
      nextInspectionDate: daysAgo(2), // Overdue
      maintenanceRecommended: true
    },
    lifecycleStatus: 'Under Maintenance',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BR-GJ-RJK-00009',
    name: 'Aji River RCC 4-Lane Bridge - Rajkot South',
    description: 'Connecting Rajkot city center with Bhavnagar Highway across River Aji.',
    category: 'Bridges',
    type: 'RCC Girder Bridge',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Rajkot Circle' },
    administrative: { state: 'Gujarat', region: 'Saurashtra', district: 'Rajkot', taluka: 'Rajkot Urban', division: 'Rajkot Division', subdivision: 'South Sub-unit' },
    location: { address: 'Chunarwad Aji Bridge, Bhavnagar Road', landmark: 'Aji Dam downstream 3km', latitude: 22.2980, longitude: 70.8250 },
    construction: { year: 2008, commissioningDate: new Date('2008-01-26'), originalCost: 2100, contractor: 'Patel Infrastructure Pvt Ltd', designLife: 60 },
    technical: { spanCount: 8, lengthMeters: 310, widthMeters: 16.5, loadClass: 'IRC Class 70R' },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 74,
      status: 'Fair',
      components: { physical: 30, safety: 15, age: 10, findings: 12, usage: 7, physicalRating: 4, safetyRating: 4 },
      lastInspectionDate: daysAgo(150),
      nextInspectionDate: daysFromNow(215),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BR-GJ-GNR-00010',
    name: 'Gandhinagar Indroda Sabarmati Barrage Bridge',
    description: 'Multi-functional barrage cum roadway bridge over Sabarmati connecting Gandhinagar Capital Complex and Dholakuva.',
    category: 'Bridges',
    type: 'Composite Steel-Concrete Girder',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Capital Projects Division' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Gandhinagar', taluka: 'Gandhinagar', division: 'Capital Projects Division', subdivision: 'Sector 7' },
    location: { address: 'Indroda Park Barrage Road', landmark: 'Adjacent to Indroda Nature Park', latitude: 23.2080, longitude: 72.6620 },
    construction: { year: 2015, commissioningDate: new Date('2015-05-01'), originalCost: 5600, contractor: 'Dilip Buildcon Gujarat Division', designLife: 65 },
    technical: { spanCount: 14, lengthMeters: 560, widthMeters: 18.0, loadClass: 'IRC Class 70R' },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 83,
      status: 'Good',
      components: { physical: 33, safety: 17, age: 12, findings: 14, usage: 7, physicalRating: 4, safetyRating: 4 },
      lastInspectionDate: daysAgo(80),
      nextInspectionDate: daysFromNow(285),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },

  // ===================== ROADS =====================
  {
    assetId: 'RD-GJ-AHM-00001',
    name: 'SG Highway 6-Lane Expressway Corridor (SH-171)',
    description: 'High-density arterial expressway connecting Sarkhej, Thaltej, Vaishnodevi circle to Gandhinagar city gate.',
    category: 'Roads',
    type: '6-Lane Divided Expressway',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Ahmedabad Division' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Ahmedabad', taluka: 'Ghatlodiya', division: 'Ahmedabad Highway Division', subdivision: 'SG Road Cell' },
    location: { address: 'Sarkhej - Gandhinagar Highway', landmark: 'Vaishnodevi Circle to Iscon Cross Road', latitude: 23.0728, longitude: 72.5132 },
    construction: { year: 2021, commissioningDate: new Date('2021-06-20'), originalCost: 89000, contractor: 'Dilip Buildcon Gujarat Division', designLife: 30 },
    technical: { lengthKm: 28.5, laneCount: 6, pavementType: 'Bituminous / SMA Wearing Course', rightOfWayMeters: 60 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 90,
      status: 'Good',
      components: { physical: 37, safety: 18, age: 14, findings: 15, usage: 6, physicalRating: 5, safetyRating: 5 },
      lastInspectionDate: daysAgo(50),
      nextInspectionDate: daysFromNow(315),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'RD-GJ-AHM-00002',
    name: 'SP Ring Road East Spur - Naroda to Nikol Section',
    description: 'Sardar Patel Peripheral Expressway carrying heavy commercial transit around Ahmedabad agglomeration.',
    category: 'Roads',
    type: '4-Lane Bypass Highway',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'AUDA & R&B Joint Authority' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Ahmedabad', taluka: 'Naroda', division: 'East Ring Road Division', subdivision: 'Subdivision 3' },
    location: { address: 'Sardar Patel Ring Road, Nikol Toll Plaza', landmark: 'Near Dastan Farm Circle', latitude: 23.0112, longitude: 72.6394 },
    construction: { year: 2014, commissioningDate: new Date('2014-09-12'), originalCost: 24500, contractor: 'Sadbhav Engineering Ltd', designLife: 25 },
    technical: { lengthKm: 18.2, laneCount: 4, pavementType: 'Dense Bituminous Macadam', rightOfWayMeters: 45 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 68,
      status: 'Fair',
      components: { physical: 27, safety: 14, age: 10, findings: 10, usage: 7, physicalRating: 3, safetyRating: 4 },
      lastInspectionDate: daysAgo(140),
      nextInspectionDate: daysFromNow(225),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'RD-GJ-SRT-00003',
    name: 'Surat-Dumas High-Capacity Coastal Corridor (SH-168)',
    description: 'Connecting Surat Diamond Bourse, Airport, and Dumas port suburb. Experiences saline coastal air exposure.',
    category: 'Roads',
    type: '4-Lane Coastal State Highway',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Surat Division' },
    administrative: { state: 'Gujarat', region: 'South Gujarat', district: 'Surat', taluka: 'Chorasi', division: 'Surat Coastal Division', subdivision: 'Dumas Sub-unit' },
    location: { address: 'Dumas Road, Piplod - Sultanpur', landmark: 'Surat Airport Approach', latitude: 21.1150, longitude: 72.7650 },
    construction: { year: 2016, commissioningDate: new Date('2016-12-10'), originalCost: 16800, contractor: 'Patel Infrastructure Pvt Ltd', designLife: 25 },
    technical: { lengthKm: 16.4, laneCount: 4, pavementType: 'Asphalt Concrete with Polymer Modifier', rightOfWayMeters: 40 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 75,
      status: 'Fair',
      components: { physical: 30, safety: 16, age: 11, findings: 12, usage: 6, physicalRating: 4, safetyRating: 4 },
      lastInspectionDate: daysAgo(85),
      nextInspectionDate: daysFromNow(280),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'RD-GJ-VDR-00004',
    name: 'Vadodara-Halol 4-Lane Industrial Highway (SH-87)',
    description: 'Heavily traversed chemical and auto manufacturing corridor connecting Vadodara with Halol GIDC.',
    category: 'Roads',
    type: '4-Lane Toll State Highway',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'Gujarat Road Infrastructure Co & R&B' },
    administrative: { state: 'Gujarat', region: 'Central Gujarat', district: 'Vadodara', taluka: 'Waghodia', division: 'Vadodara Highway Division', subdivision: 'Halol Toll Wing' },
    location: { address: 'Vadodara-Halol Toll Road, Golden Chowkdi to Jarod', landmark: 'Near Waghodia Crossings', latitude: 22.3550, longitude: 73.3100 },
    construction: { year: 2019, commissioningDate: new Date('2019-02-14'), originalCost: 31200, contractor: 'Dilip Buildcon Gujarat Division', designLife: 30 },
    technical: { lengthKm: 32.0, laneCount: 4, pavementType: 'Rigid Concrete Pavement', rightOfWayMeters: 50 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 87,
      status: 'Good',
      components: { physical: 35, safety: 17, age: 14, findings: 15, usage: 6, physicalRating: 4, safetyRating: 5 },
      lastInspectionDate: daysAgo(70),
      nextInspectionDate: daysFromNow(295),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'RD-GJ-RJK-00005',
    name: 'Rajkot Urban Ring Road - Phase II (Kalawad Radial)',
    description: 'Bypass corridor redirecting inter-district traffic around Rajkot AIIMS and Saurashtra University.',
    category: 'Roads',
    type: '4-Lane Radial Ring Road',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Rajkot Circle' },
    administrative: { state: 'Gujarat', region: 'Saurashtra', district: 'Rajkot', taluka: 'Lodhika', division: 'Rajkot Ring Road Division', subdivision: 'Subdivision 2' },
    location: { address: '150 Feet Ring Road Extension, Kalawad Road', landmark: 'Near AIIMS Rajkot Junction', latitude: 22.2850, longitude: 70.7710 },
    construction: { year: 2020, commissioningDate: new Date('2020-11-20'), originalCost: 19500, contractor: 'Patel Infrastructure Pvt Ltd', designLife: 30 },
    technical: { lengthKm: 14.8, laneCount: 4, pavementType: 'Semi-Dense Bituminous Concrete', rightOfWayMeters: 45 },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 85,
      status: 'Good',
      components: { physical: 34, safety: 17, age: 13, findings: 14, usage: 7, physicalRating: 4, safetyRating: 4 },
      lastInspectionDate: daysAgo(105),
      nextInspectionDate: daysFromNow(260),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'RD-GJ-BRC-00007',
    name: 'Bharuch-Dahej PCPIR Heavy Freight Expressway',
    description: 'Petrochemical corridor catering to multi-axle chemical tankers and port cargo; severe heavy rutting observed.',
    category: 'Roads',
    type: '4-Lane Industrial Freight Road',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'GIDC Infrastructure & R&B Department' },
    administrative: { state: 'Gujarat', region: 'South-Central Gujarat', district: 'Bharuch', taluka: 'Vagra', division: 'Dahej PCPIR Division', subdivision: 'Dahej Sub-unit' },
    location: { address: 'SH-6 Bharuch-Dahej Industrial Road', landmark: 'Near Vilayat GIDC Gate', latitude: 21.7100, longitude: 72.8500 },
    construction: { year: 2011, commissioningDate: new Date('2011-04-18'), originalCost: 28400, contractor: 'Sadbhav Engineering Ltd', designLife: 20 },
    technical: { lengthKm: 42.5, laneCount: 4, pavementType: 'Heavy Bituminous Pavement', rightOfWayMeters: 45 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 44,
      status: 'Poor',
      components: { physical: 17, safety: 10, age: 4, findings: 8, usage: 5, physicalRating: 2, safetyRating: 3 },
      lastInspectionDate: daysAgo(30),
      nextInspectionDate: daysAgo(8), // Overdue
      maintenanceRecommended: true
    },
    lifecycleStatus: 'Under Maintenance',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'RD-GJ-GNR-00006',
    name: 'Gandhinagar-Koba Aerodrome Green Corridor',
    description: 'Prestige 8-lane boulevard connecting Gandhinagar Capital Core with SVPI International Airport.',
    category: 'Roads',
    type: '8-Lane Landscaped Boulevard',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Capital Projects Division' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Gandhinagar', taluka: 'Gandhinagar', division: 'Capital Projects Division', subdivision: 'Boulevard Cell' },
    location: { address: 'Airport-Koba-Gandhinagar Road', landmark: 'Koba Circle to Bhaijipura', latitude: 23.1670, longitude: 72.6280 },
    construction: { year: 2021, commissioningDate: new Date('2021-01-10'), originalCost: 45000, contractor: 'PSP Projects Ltd', designLife: 40 },
    technical: { lengthKm: 12.0, laneCount: 8, pavementType: 'Mastic Asphalt & Stone Matrix', rightOfWayMeters: 75 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 94,
      status: 'Good',
      components: { physical: 39, safety: 19, age: 14, findings: 15, usage: 7, physicalRating: 5, safetyRating: 5 },
      lastInspectionDate: daysAgo(40),
      nextInspectionDate: daysFromNow(325),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'RD-GJ-MSN-00008',
    name: 'Mehsana-Unjha Agricultural Corridor (SH-41)',
    description: 'Vital farm-to-mandi corridor carrying heavy grain and spice trailers between Mehsana and Unjha APMC.',
    category: 'Roads',
    type: '4-Lane State Highway',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Mehsana Division' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Mehsana', taluka: 'Unjha', division: 'Mehsana Highway Division', subdivision: 'Subdivision 1' },
    location: { address: 'SH-41 Unjha Bypass Highway', landmark: 'Near Unjha APMC Gate', latitude: 23.6800, longitude: 72.3850 },
    construction: { year: 2017, commissioningDate: new Date('2017-08-11'), originalCost: 14200, contractor: 'Sadbhav Engineering Ltd', designLife: 25 },
    technical: { lengthKm: 26.0, laneCount: 4, pavementType: 'Bituminous Concrete', rightOfWayMeters: 35 },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 81,
      status: 'Good',
      components: { physical: 32, safety: 16, age: 12, findings: 14, usage: 7, physicalRating: 4, safetyRating: 4 },
      lastInspectionDate: daysAgo(95),
      nextInspectionDate: daysFromNow(270),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },

  // ===================== GOVERNMENT BUILDINGS =====================
  {
    assetId: 'BLD-GJ-GNR-00001',
    name: 'Swarnim Sankul 1 - Gujarat CM Secretariat Complex',
    description: 'State Executive headquarters housing the Offices of the Chief Minister, Cabinet Ministers, and Chief Secretary.',
    category: 'Government Buildings',
    type: 'Administrative Secretariat Bhavan',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Capital Special Project Division' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Gandhinagar', taluka: 'Gandhinagar', division: 'Sachivalaya Maintenance Division', subdivision: 'Executive Wing' },
    location: { address: 'Sector 10, New Sachivalaya Campus', landmark: 'Opposite Mahatma Mandir', latitude: 23.2238, longitude: 72.6575 },
    construction: { year: 2014, commissioningDate: new Date('2014-04-20'), originalCost: 26000, contractor: 'PSP Projects Ltd', designLife: 100 },
    technical: { floorCount: 5, builtUpSqMeters: 45000, seismicZone: 'Zone III compliant', hvacType: 'Central Chiller VRV' },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 95,
      status: 'Good',
      components: { physical: 40, safety: 20, age: 14, findings: 15, usage: 6, physicalRating: 5, safetyRating: 5 },
      lastInspectionDate: daysAgo(30),
      nextInspectionDate: daysFromNow(335),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BLD-GJ-GNR-00002',
    name: 'Gujarat New Sachivalaya Complex - Block 4 & 5',
    description: 'Central Administrative Secretariat blocks housing Revenue, Finance, and Public Works ministerial offices.',
    category: 'Government Buildings',
    type: 'Multi-Storey Secretariat Complex',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Capital Maintenance Division' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Gandhinagar', taluka: 'Gandhinagar', division: 'Capital Maintenance Division', subdivision: 'Block Maintenance 4-5' },
    location: { address: 'Sector 10, Sachivalaya Complex', landmark: 'Gate No. 2, Gandhinagar', latitude: 23.2201, longitude: 72.6542 },
    construction: { year: 1985, commissioningDate: new Date('1985-06-15'), originalCost: 4500, contractor: 'Government Works R&B', designLife: 75 },
    technical: { floorCount: 7, builtUpSqMeters: 62000, seismicZone: 'Zone III upgraded', hvacType: 'Decentralized Package Units' },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 66,
      status: 'Fair',
      components: { physical: 26, safety: 14, age: 8, findings: 11, usage: 7, physicalRating: 3, safetyRating: 3 },
      lastInspectionDate: daysAgo(160),
      nextInspectionDate: daysFromNow(205),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BLD-GJ-AHM-00003',
    name: 'Gujarat High Court Infrastructure Complex, Sola',
    description: 'Apex judicial complex of Gujarat state with 42 courtrooms, advocate chambers, and digitized record repository.',
    category: 'Government Buildings',
    type: 'Judicial Headquarters Complex',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B High Court Project Division' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Ahmedabad', taluka: 'Ghatlodiya', division: 'Ahmedabad Judicial Infra Division', subdivision: 'Sola Court Wing' },
    location: { address: 'SG Highway, Sola', landmark: 'Opposite Sola Civil Hospital', latitude: 23.0821, longitude: 72.5284 },
    construction: { year: 1999, commissioningDate: new Date('1999-01-16'), originalCost: 12500, contractor: 'PSP Projects Ltd', designLife: 100 },
    technical: { floorCount: 4, builtUpSqMeters: 78000, seismicZone: 'Zone III reinforced', fireSystem: 'Automated Sprinkler + Hydrant' },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 84,
      status: 'Good',
      components: { physical: 34, safety: 17, age: 12, findings: 14, usage: 7, physicalRating: 4, safetyRating: 4 },
      lastInspectionDate: daysAgo(75),
      nextInspectionDate: daysFromNow(290),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BLD-GJ-AHM-00004',
    name: 'R&B State Central Quality Control & Testing Laboratory',
    description: 'State apex materials testing, soil mechanics, and bitumen quality certification laboratory facility.',
    category: 'Government Buildings',
    type: 'Technical Testing & Research Bhavan',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'Chief Engineer (QC), R&B Department' },
    administrative: { state: 'Gujarat', region: 'Central Gujarat', district: 'Ahmedabad', taluka: 'Ellisbridge', division: 'Quality Control Wing', subdivision: 'Lab Sector' },
    location: { address: 'Near Gujarat College, Ellisbridge', landmark: 'Adjacent to R&B Regional Workshop', latitude: 23.0450, longitude: 72.5510 },
    construction: { year: 2007, commissioningDate: new Date('2007-09-05'), originalCost: 1850, contractor: 'Sadbhav Infra Works', designLife: 50 },
    technical: { floorCount: 3, builtUpSqMeters: 8500, labs: 'Bitumen, Concrete, Steel, Geo-tech' },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 79,
      status: 'Fair',
      components: { physical: 31, safety: 16, age: 10, findings: 15, usage: 7, physicalRating: 4, safetyRating: 4 },
      lastInspectionDate: daysAgo(100),
      nextInspectionDate: daysFromNow(265),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BLD-GJ-SRT-00005',
    name: 'District Collectorate & Administrative Towers, Surat',
    description: 'Integrated revenue administration complex serving Surat metropolitan district and coastal talukas.',
    category: 'Government Buildings',
    type: 'Twin-Tower Administrative Complex',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Surat' },
    administrative: { state: 'Gujarat', region: 'South Gujarat', district: 'Surat', taluka: 'Chorasi', division: 'Surat Building Division', subdivision: 'Collectorate Cell' },
    location: { address: 'Nanpura, Dutch Garden Road', landmark: 'Near Tapi Riverfront Walk', latitude: 21.1890, longitude: 72.8210 },
    construction: { year: 2011, commissioningDate: new Date('2011-12-25'), originalCost: 9800, contractor: 'Patel Infrastructure Pvt Ltd', designLife: 75 },
    technical: { floorCount: 8, builtUpSqMeters: 38000, solarPowerKW: 150 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 82,
      status: 'Good',
      components: { physical: 33, safety: 17, age: 12, findings: 13, usage: 7, physicalRating: 4, safetyRating: 4 },
      lastInspectionDate: daysAgo(115),
      nextInspectionDate: daysFromNow(250),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BLD-GJ-RJK-00007',
    name: 'Saurashtra Regional Civil Hospital & Multi-Specialty Wing',
    description: '1,200-bed government apex tertiary care teaching hospital complex catering to Rajkot, Jamnagar, and Morbi.',
    category: 'Government Buildings',
    type: 'Healthcare Infrastructure Complex',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Health Infrastructure Wing' },
    administrative: { state: 'Gujarat', region: 'Saurashtra', district: 'Rajkot', taluka: 'Rajkot', division: 'Rajkot Building Division', subdivision: 'Hospital Maintenance Wing' },
    location: { address: 'Jamnagar Road, Near Civil Hospital Chowk', landmark: 'Adjacent to PDU Medical College', latitude: 22.3020, longitude: 70.7950 },
    construction: { year: 1995, commissioningDate: new Date('1995-10-02'), originalCost: 8200, contractor: 'PSP Projects Ltd', designLife: 75 },
    technical: { bedCapacity: 1200, floorCount: 6, builtUpSqMeters: 92000, oxygenPlantCount: 3 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 63,
      status: 'Fair',
      components: { physical: 25, safety: 13, age: 9, findings: 10, usage: 6, physicalRating: 3, safetyRating: 3 },
      lastInspectionDate: daysAgo(130),
      nextInspectionDate: daysFromNow(235),
      maintenanceRecommended: true
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BLD-GJ-VDR-00006',
    name: 'Vadodara Circle R&B Executive Engineering Complex',
    description: 'Divisional design, estimation, and quality assurance office compound for Vadodara, Anand, and Chhota Udaipur.',
    category: 'Government Buildings',
    type: 'Divisional Engineering Office',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'Superintending Engineer, R&B Vadodara' },
    administrative: { state: 'Gujarat', region: 'Central Gujarat', district: 'Vadodara', taluka: 'Vadodara Urban', division: 'Vadodara Circle HQ', subdivision: 'HQ Unit' },
    location: { address: 'Kothi Compound, Raopura', landmark: 'Near Nyay Mandir', latitude: 22.3120, longitude: 73.1900 },
    construction: { year: 1982, commissioningDate: new Date('1982-03-22'), originalCost: 950, contractor: 'Government Works R&B', designLife: 60 },
    technical: { floorCount: 3, builtUpSqMeters: 14500 },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 58,
      status: 'Poor',
      components: { physical: 23, safety: 12, age: 6, findings: 10, usage: 7, physicalRating: 3, safetyRating: 3 },
      lastInspectionDate: daysAgo(42),
      nextInspectionDate: daysAgo(4), // Overdue
      maintenanceRecommended: true
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'BLD-GJ-MSN-00009',
    name: 'Mehsana District Poly-Engineering & IT Bhavan',
    description: 'Newly constructed technical skill development and government departmental training complex.',
    category: 'Government Buildings',
    type: 'Institutional Academic Bhavan',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Mehsana' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Mehsana', taluka: 'Mehsana', division: 'Mehsana Building Division', subdivision: 'Subdivision 2' },
    location: { address: 'State Highway Road, Nagalpur', landmark: 'Near Mehsana Railway Bypass', latitude: 23.5950, longitude: 72.3750 },
    construction: { year: 2021, commissioningDate: new Date('2021-09-05'), originalCost: 3800, contractor: 'PSP Projects Ltd', designLife: 60 },
    technical: { floorCount: 4, builtUpSqMeters: 22000, smartClassrooms: 16 },
    usage: { trafficImportance: 'Low' },
    condition: {
      score: 91,
      status: 'Good',
      components: { physical: 37, safety: 19, age: 14, findings: 15, usage: 6, physicalRating: 5, safetyRating: 5 },
      lastInspectionDate: daysAgo(65),
      nextInspectionDate: daysFromNow(300),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },

  // ===================== CULVERTS =====================
  {
    assetId: 'CV-GJ-AHM-00001',
    name: 'Khari Cut Canal Reinforced Box Culvert No. 12',
    description: 'Twin-cell RCC box culvert traversing heavy urban arterial, suffering from structural slab deformation and sediment choking.',
    category: 'Culverts',
    type: 'Twin Cell RCC Box Culvert',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Ahmedabad Division' },
    administrative: { state: 'Gujarat', region: 'Central Gujarat', district: 'Ahmedabad', taluka: 'Vatva', division: 'Ahmedabad South Division', subdivision: 'Canal Cell' },
    location: { address: 'Khari Cut Canal Road, Vatva Industrial Crossings', landmark: 'Near GIDC Phase 2', latitude: 22.9810, longitude: 72.6105 },
    construction: { year: 1988, commissioningDate: new Date('1988-04-10'), originalCost: 180, contractor: 'Cube Construction Engineering Ltd', designLife: 40 },
    technical: { spanMeters: 6.5, ventCount: 2, heightMeters: 3.2, barrelLengthMeters: 24.0 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 28,
      status: 'Critical',
      components: { physical: 10, safety: 6, age: 2, findings: 5, usage: 5, physicalRating: 1, safetyRating: 2 },
      lastInspectionDate: daysAgo(15),
      nextInspectionDate: daysAgo(3), // Overdue
      maintenanceRecommended: true
    },
    lifecycleStatus: 'Under Maintenance',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'CV-GJ-GNR-00002',
    name: 'Capital City Sector-14 Stormwater RCC Culvert',
    description: 'High-discharge box culvert draining Gandhinagar north sectors into the Sabarmati drainage reservoir.',
    category: 'Culverts',
    type: 'Single Cell Box Culvert',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Capital Projects Division' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Gandhinagar', taluka: 'Gandhinagar', division: 'Capital Drainage Division', subdivision: 'North Sector' },
    location: { address: 'GH Road Cross Section, Sector 14', landmark: 'Near Sector 14 Sports Complex', latitude: 23.2290, longitude: 72.6450 },
    construction: { year: 2012, commissioningDate: new Date('2012-07-20'), originalCost: 320, contractor: 'Cube Construction Engineering Ltd', designLife: 50 },
    technical: { spanMeters: 4.5, ventCount: 1, heightMeters: 2.8, barrelLengthMeters: 35.0 },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 77,
      status: 'Fair',
      components: { physical: 31, safety: 16, age: 11, findings: 12, usage: 7, physicalRating: 4, safetyRating: 4 },
      lastInspectionDate: daysAgo(140),
      nextInspectionDate: daysFromNow(225),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'CV-GJ-SRT-00003',
    name: 'Mindhola River Tributary Box Culvert 08',
    description: 'Multiple-pipe culvert with heavy coastal tidal surge; scouring observed along downstream aprons.',
    category: 'Culverts',
    type: 'Multi-Cell Pipe & Box Culvert',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Surat' },
    administrative: { state: 'Gujarat', region: 'South Gujarat', district: 'Surat', taluka: 'Palsana', division: 'Surat Rural Division', subdivision: 'Subdivision 4' },
    location: { address: 'Palsana-Sachin Link Road, Mindhola Crossing', landmark: 'Near Sachin GIDC Outskirts', latitude: 21.0850, longitude: 72.8750 },
    construction: { year: 1997, commissioningDate: new Date('1997-11-04'), originalCost: 240, contractor: 'Patel Infrastructure Pvt Ltd', designLife: 40 },
    technical: { spanMeters: 8.0, ventCount: 3, heightMeters: 2.5, barrelLengthMeters: 18.0 },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 47,
      status: 'Poor',
      components: { physical: 18, safety: 10, age: 5, findings: 8, usage: 6, physicalRating: 2, safetyRating: 3 },
      lastInspectionDate: daysAgo(50),
      nextInspectionDate: daysAgo(12), // Overdue
      maintenanceRecommended: true
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'CV-GJ-VDR-00004',
    name: 'Vishwamitri Overflow Relief Box Culvert, Manjalpur',
    description: 'Triple cell stormwater diversion structure; excessive cavity formation detected below wing walls.',
    category: 'Culverts',
    type: 'Triple Cell RCC Culvert',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Vadodara' },
    administrative: { state: 'Gujarat', region: 'Central Gujarat', district: 'Vadodara', taluka: 'Vadodara South', division: 'Vadodara Drainage Division', subdivision: 'Manjalpur Wing' },
    location: { address: 'Manjalpur Main Road to Tarsali Ring', landmark: 'Adjacent to Vishwamitri Flood Channel', latitude: 22.2750, longitude: 73.1950 },
    construction: { year: 1993, commissioningDate: new Date('1993-06-25'), originalCost: 290, contractor: 'Cube Construction Engineering Ltd', designLife: 40 },
    technical: { spanMeters: 12.0, ventCount: 3, heightMeters: 3.5, barrelLengthMeters: 28.0 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 35,
      status: 'Critical',
      components: { physical: 14, safety: 7, age: 3, findings: 6, usage: 5, physicalRating: 2, safetyRating: 2 },
      lastInspectionDate: daysAgo(18),
      nextInspectionDate: daysAgo(6), // Overdue
      maintenanceRecommended: true
    },
    lifecycleStatus: 'Under Maintenance',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'CV-GJ-BRC-00005',
    name: 'Amla Khadi Industrial Drain RCC Culvert No. 03',
    description: 'Box culvert channeling industrial effluents across freight rail approach road in Bharuch GIDC.',
    category: 'Culverts',
    type: 'RCC Slab Culvert',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Department, Bharuch' },
    administrative: { state: 'Gujarat', region: 'South-Central Gujarat', district: 'Bharuch', taluka: 'Bharuch', division: 'Bharuch Industrial Cell', subdivision: 'Amla Sector' },
    location: { address: 'Old National Highway Crossing, Amla Khadi', landmark: 'Near GNFC Industrial Complex', latitude: 21.6850, longitude: 73.0120 },
    construction: { year: 2005, commissioningDate: new Date('2005-08-30'), originalCost: 195, contractor: 'Sadbhav Infra Works', designLife: 45 },
    technical: { spanMeters: 5.0, ventCount: 1, heightMeters: 2.2, barrelLengthMeters: 22.0 },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 70,
      status: 'Fair',
      components: { physical: 28, safety: 14, age: 10, findings: 11, usage: 7, physicalRating: 3, safetyRating: 4 },
      lastInspectionDate: daysAgo(135),
      nextInspectionDate: daysFromNow(230),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },

  // ===================== OTHER STRUCTURES =====================
  {
    assetId: 'STR-GJ-GNR-00001',
    name: 'Mahatma Mandir Convention Center Structural Canopy',
    description: 'Prestressed tensile cable and steel space frame canopy at Gujarat international convention center.',
    category: 'Other Structures',
    type: 'Tensile Cable Space Frame',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Capital Special Projects' },
    administrative: { state: 'Gujarat', region: 'North Gujarat', district: 'Gandhinagar', taluka: 'Gandhinagar', division: 'Capital Projects Division', subdivision: 'Convention Sector' },
    location: { address: 'Sector 13C, Mahatma Mandir Campus', landmark: 'Opposite Gandhinagar Railway Station', latitude: 23.2350, longitude: 72.6390 },
    construction: { year: 2011, commissioningDate: new Date('2011-01-10'), originalCost: 13500, contractor: 'Larsen & Toubro Heavy Civil Infra', designLife: 80 },
    technical: { canopyAreaSqMeters: 18000, heightMeters: 24.0, membraneType: 'PTFE Architectural Fabric' },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 93,
      status: 'Good',
      components: { physical: 38, safety: 19, age: 14, findings: 15, usage: 7, physicalRating: 5, safetyRating: 5 },
      lastInspectionDate: daysAgo(45),
      nextInspectionDate: daysFromNow(320),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'STR-GJ-AHM-00002',
    name: 'Sabarmati Riverfront Promenade Retaining Wall & Barrage',
    description: 'Sheet pile diaphragm and reinforced concrete river protection walls controlling water levels and flood resilience.',
    category: 'Other Structures',
    type: 'Diaphragm Retaining Wall & Barrage',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'SRFDCL & R&B Water Infra Unit' },
    administrative: { state: 'Gujarat', region: 'Central Gujarat', district: 'Ahmedabad', taluka: 'Daskroi', division: 'Ahmedabad Riverfront Wing', subdivision: 'Promenade South' },
    location: { address: 'Sabarmati Riverfront East Promenade, Vasna to Usmanpura', landmark: 'Near Vasna Barrage Outfall', latitude: 23.0315, longitude: 72.5750 },
    construction: { year: 2013, commissioningDate: new Date('2013-10-15'), originalCost: 42000, contractor: 'PSP Projects Ltd', designLife: 100 },
    technical: { lengthMeters: 11500, wallHeightMeters: 9.5, floodRetentionDischargeCusecs: 475000 },
    usage: { trafficImportance: 'High' },
    condition: {
      score: 89,
      status: 'Good',
      components: { physical: 36, safety: 18, age: 14, findings: 14, usage: 7, physicalRating: 5, safetyRating: 4 },
      lastInspectionDate: daysAgo(55),
      nextInspectionDate: daysFromNow(310),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'STR-GJ-SRT-00003',
    name: 'Dumas Sea Wall & Coastal Erosion Barrier',
    description: 'Armored tetrapod embankment and boulder sea wall protecting southern Surat coastal settlements from Arabian Sea surge.',
    category: 'Other Structures',
    type: 'Tetrapod Revetment & Sea Wall',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'R&B Marine & Coastal Division, Surat' },
    administrative: { state: 'Gujarat', region: 'South Gujarat', district: 'Surat', taluka: 'Chorasi', division: 'Surat Coastal Division', subdivision: 'Dumas Marine Cell' },
    location: { address: 'Dumas Beach Road, Sultanpur Shoreline', landmark: 'Dumas Anchor Point', latitude: 21.0720, longitude: 72.7150 },
    construction: { year: 2016, commissioningDate: new Date('2016-03-28'), originalCost: 7800, contractor: 'Sadbhav Engineering Ltd', designLife: 50 },
    technical: { barrierLengthKm: 4.8, crestLevelMeters: 7.2, tetrapodWeightTonnes: 12 },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 76,
      status: 'Fair',
      components: { physical: 30, safety: 15, age: 11, findings: 13, usage: 7, physicalRating: 4, safetyRating: 4 },
      lastInspectionDate: daysAgo(90),
      nextInspectionDate: daysFromNow(275),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  },
  {
    assetId: 'STR-GJ-RJK-00004',
    name: 'Nyari Dam Spillway Gate Gantries & Deck Structure',
    description: 'Structural steel crest gantry and radial gate overpass supporting emergency reservoir discharge control.',
    category: 'Other Structures',
    type: 'Hydraulic Spillway Gantry Structure',
    department: 'Roads & Buildings Department',
    ownership: { owner: 'Government of Gujarat', managingAuthority: 'Irrigation & R&B Joint Circle, Rajkot' },
    administrative: { state: 'Gujarat', region: 'Saurashtra', district: 'Rajkot', taluka: 'Lodhika', division: 'Rajkot Water Structures', subdivision: 'Nyari Sector' },
    location: { address: 'Nyari-1 Dam, Kalawad Highway Approach', landmark: 'Nyari Dam Main Crest', latitude: 22.2610, longitude: 70.7420 },
    construction: { year: 2002, commissioningDate: new Date('2002-09-18'), originalCost: 1650, contractor: 'Cube Construction Engineering Ltd', designLife: 60 },
    technical: { radialGates: 8, gantrySpanMeters: 85, hoistingCapacityTonnes: 50 },
    usage: { trafficImportance: 'Medium' },
    condition: {
      score: 71,
      status: 'Fair',
      components: { physical: 28, safety: 14, age: 9, findings: 13, usage: 7, physicalRating: 3, safetyRating: 4 },
      lastInspectionDate: daysAgo(110),
      nextInspectionDate: daysFromNow(255),
      maintenanceRecommended: false
    },
    lifecycleStatus: 'Operational',
    archived: false,
    isDemo: true
  }
];

module.exports = {
  contractorsData,
  usersData,
  assetsData,
  daysAgo,
  daysFromNow
};
